-- v0.2.52 V52-AG: schema version tracking for derived state
--
-- ## Why
--
-- Pre-V52-AG, the launcher had NO way to know "this Weaviate collection
-- was generated by analyzer/installer vN; the canonical shape is now vM;
-- it needs to be re-generated." Every schema change required either:
--   (a) an ad-hoc migration script that knew which artifacts to touch
--       (e.g. `migrate-development-temporal-props.sh` for V52-I);
--   (b) the user noticing something's broken + asking us;
--   (c) the orchestrator silently producing garbage results (e.g. the
--       V52-O.3 UUID5 collision + V52-O.7 prune-stale destruction that
--       drove orchestrator-root's CodeFunction collection to 0 Python
--       rows over 22 days of incremental writes).
--
-- V52-AG introduces explicit version tracking for every DERIVED artifact
-- (Weaviate collections, code-graph indices, bundle materialization,
-- per-row JSON-content shapes, controlled-vocabulary columns). Install +
-- update flows compare the stored version against the canonical constants
-- in `vco_lib/schema_versions.py` and trigger drop+recreate (or in-place
-- migration for user-curated content) when stale.
--
-- ## Design contract (user-locked 2026-06-09)
--
-- "From now on consistent" — one canonical shape per artifact, no
-- back-compat layers. When a future release ever changes a shape, it
-- bumps the constant + the install/update flow drop+recreates (for
-- derived state) or upgrade-in-place (for user-curated state). NO
-- migration ladders, NO parallel-table back-compat, NO "if version X
-- then patch" branches in callers.
--
-- ## Table shape
--
-- ONE registry table covering ALL versioned artifacts, keyed by
-- (project_id, artifact_type, artifact_name). NULL project_id is the
-- sentinel for orchestrator-wide artifacts (launcher-DB table-set
-- version, rl_events payload shape, shared module-settings shape, etc.).
--
-- artifact_type vocabulary (initial v0.2.52 set; future versions extend):
--   - 'kg_collection'                — per-project KG class (V52-I bump → v3)
--   - 'shared_kg_collection'         — VibeCodedOrchestrator_KnowledgeGraph (V52-I → v3)
--   - 'diagrams_collection'          — per-project Diagrams class (V52-I → v2)
--   - 'development_collection'       — per-project Development class (V52-I → v2)
--   - 'codegraph_collection'         — any of CodeFunction/Class/Module/API/Interaction (V52-O.3+O.4 → v4)
--   - 'kg_node_frontmatter'          — per-project KG node corpus content schema (v0.2.52 introduces → v1)
--   - 'bundle_materialization'       — existing _MANIFEST_SCHEMA_VERSION (currently v2; no change in v0.2.52)
--   - 'project_kg_bindings_shape'    — JSON shape of project_kg_bindings.config_json (v1)
--   - 'project_codegraph_bindings_shape' — similar (v1)
--   - 'module_installs_shape'        — kg_collections JSON shape (v1)
--   - 'module_settings_shape'        — setting_value JSON shape (v1)
--   - 'codegraph_access_vocabulary'  — access_level value set (v1: 'none'/'read'/'write')
--   - 'kg_collection_access_vocabulary' — same (v1)
--   - 'code_graph_builds_status_vocabulary' — status value set (v1)
--   - 'project_bootstrap_version'    — cross-table invariants this project was bootstrapped against (v1)
--   - 'rl_events_payload_shape'      — already v3 per existing contract (formalized here, NULL project_id)
--   - 'launcher_db_table_set'        — matches _schema_migrations max version (NULL project_id)
--
-- artifact_name:
--   - For per-collection artifacts: the actual Weaviate class name (e.g.
--     'VCODev_KnowledgeGraph', 'VibeCodedOrchestrator_CodeFunction').
--   - For per-table-shape artifacts: '*' (one row per project covering
--     all rows of that shape) or a specific row identifier when
--     fine-grained tracking matters.
--   - For project-wide bootstrap: 'main'.
--
-- schema_version:
--   - INTEGER, monotonically increasing per (artifact_type) lineage.
--   - Compared to the canonical constant in vco_lib/schema_versions.py.
--   - schema_version < canonical → install/update triggers recreate.
--   - schema_version > canonical → refuse to start (user downgraded
--     orchestrator while on newer DB; surface clear error).
--
-- materialized_at: when this row was written (= when the artifact was
-- last (re)created at the listed version). For 'project_bootstrap_version'
-- and other orchestrator-wide artifacts, it's just the registration time.
--
-- ## Foreign keys
--
-- project_id references projects(id) with ON DELETE CASCADE — when a
-- project is removed from the launcher, its version rows go too.
--
-- ## Idempotency
--
-- The (project_id, artifact_type, artifact_name) PRIMARY KEY guarantees
-- ON CONFLICT REPLACE semantics for the install/update path's upserts.
-- Reading the table is always safe; writing happens at well-defined
-- points (project create, bundle update, collection drop+recreate).
--
-- ## Migration policy
--
-- New rows from this migration onwards. Pre-v0.2.52 projects get their
-- rows registered at v0.2.52-canonical versions THE FIRST TIME they run
-- through `install.py --update` or "Update bundle" — see V52-AG layer 4
-- in the v0.2.52 backlog. Until then their version rows are absent,
-- which the version-check helper treats as "v0 = needs initial
-- materialization" (which the existing install paths already trigger
-- for collections that don't exist yet).
--
-- ## Future-proofing
--
-- New artifact_type entries don't require new migrations — they're
-- registered by install/update code paths at runtime. The TABLE schema
-- only changes if we discover a missing column (e.g. a per-row "expected
-- canonical version" cache if comparing constants becomes hot).

CREATE TABLE artifact_schema_versions (
    -- NULL = orchestrator-wide (rl_events shape, launcher.db tableset version, etc.)
    project_id      TEXT,
    artifact_type   TEXT    NOT NULL,
    artifact_name   TEXT    NOT NULL,
    schema_version  INTEGER NOT NULL,
    materialized_at INTEGER NOT NULL,
    PRIMARY KEY (project_id, artifact_type, artifact_name),
    FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

CREATE INDEX idx_artifact_schema_versions_type
    ON artifact_schema_versions (artifact_type, schema_version);

CREATE INDEX idx_artifact_schema_versions_project
    ON artifact_schema_versions (project_id);
