# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 VibeCoded Tools
"""m5 — the missing parity leg for the KG-sync tally/finalize mirror.

The KG-sync progress contract is a **tier-C cross-language mirror**: Python
EMITS the lines (`templates/scripts/sync_knowledge_graph.py`), Rust PARSES
them (`launcher/src-tauri/src/commands/kg_sync.rs::parse_summary_line` /
`::is_finalize_line`). Both sides had unit tests — and both tested against
their OWN independently hard-coded string literals. So the emitter could
change `succeeded` to `ok`, or drop the `📊 KG:` prefix, and every suite on
both sides would stay green while the launcher silently reported
`succeeded=0, failed=<total>` for a healthy run.

The repo's A>B>C rule requires a tier-C mirror to be locked by a parity
test. This is it: it takes the literals **each side actually uses**, read
out of the two source files, and asserts the Rust matcher accepts what the
Python emitter produces — with the real numbers.

Nothing here is hard-coded on either side. Both halves are extracted:

  * Python — the `SyncTally` class is exec'd out of the shipped source, so
    `summary_fragment()` is the real method, and the `📊 …` / `📝 …` print
    literals come from the AST (docstrings and comments excluded, so the
    prose that DESCRIBES the format cannot stand in for the format).
  * Rust — the prefixes handed to `parse_summary_line`, the markers handed
    to `extract_number_before`, and `is_finalize_line`'s `starts_with`
    literal are read from `kg_sync.rs`; `extract_number_before` is ported
    verbatim so the numbers are checked, not just the substrings.

FOLLOW-UP (a future lane, not this one): the cleanest end-state is a single
committed fixture both sides read. `tests/fixtures/kg_sync_stdout_contract.json`
is written here for that purpose; the two one-line changes needed to CONSUME
it are named in this module's `_FIXTURE_ADOPTION` note.
"""
from __future__ import annotations

import ast
import json
import re
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PY_EMITTER = REPO_ROOT / "templates" / "scripts" / "sync_knowledge_graph.py"
RUST_PARSER = REPO_ROOT / "launcher/src-tauri/src/commands/kg_sync.rs"
FIXTURE = REPO_ROOT / "tests" / "fixtures" / "kg_sync_stdout_contract.json"

_FIXTURE_ADOPTION = """
To retire the source-scraping in this module, a future lane adds ONE line
per side (both files are outside this lane's write set):

  * templates/scripts/sync_knowledge_graph.py — near `SyncTally.summary_fragment`:
        #: CONTRACT: tests/fixtures/kg_sync_stdout_contract.json pins these literals.
  * launcher/src-tauri/src/commands/kg_sync.rs — above `fn parse_summary_line`:
        // CONTRACT: tests/fixtures/kg_sync_stdout_contract.json pins these literals.

The fixture itself is regenerated by this module (see `_write_fixture`), so
it can never drift from the sources it documents.
"""


# ───────────────────────────────────────────────────────────────────────────
# Python side — the real emitter, extracted from the shipped source
# ───────────────────────────────────────────────────────────────────────────


def _py_tree() -> ast.Module:
    return ast.parse(PY_EMITTER.read_text(encoding="utf-8"))


def _real_sync_tally_class():
    """Exec the shipped `SyncTally` (plus the `OUTCOME_*` constants and the
    `_NON_FAILURE_OUTCOMES` set it needs) in an isolated namespace.

    Importing the module outright is not an option — it does project-root
    resolution and `sys.exit` at import time. Re-typing the class into the
    test would defeat the purpose: the test must run the SHIPPED code.
    """
    tree = _py_tree()
    wanted_classes = {"SyncOutcome", "SyncTally"}
    nodes: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and node.name in wanted_classes:
            nodes.append(node)
        elif isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name)
            and (t.id.startswith("OUTCOME_") or t.id == "_NON_FAILURE_OUTCOMES")
            for t in node.targets
        ):
            nodes.append(node)
    missing = wanted_classes - {n.name for n in nodes if isinstance(n, ast.ClassDef)}
    assert not missing, f"shipped emitter no longer defines {missing}"

    module = ast.Module(body=nodes, type_ignores=[])
    ast.fix_missing_locations(module)
    ns: dict = {"Dict": dict, "List": list}
    exec(compile(module, str(PY_EMITTER), "exec"), ns)
    return ns["SyncOutcome"], ns["SyncTally"], ns


def _emitted_print_literals() -> dict[str, str]:
    """The leading string constant of every `print(...)` in the emitter that
    starts with one of the contract emojis.

    AST-walked, so a comment or docstring quoting `📊 KG:` cannot satisfy
    this — only a literal the module can actually PRINT.
    """
    found: dict[str, str] = {}
    for node in ast.walk(_py_tree()):
        if not (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Name)
            and node.func.id == "print"
            and node.args
        ):
            continue
        arg = node.args[0]
        if isinstance(arg, ast.JoinedStr):
            head = arg.values[0] if arg.values else None
            text = head.value if isinstance(head, ast.Constant) else None
        elif isinstance(arg, ast.Constant) and isinstance(arg.value, str):
            text = arg.value
        else:
            continue
        if not isinstance(text, str):
            continue
        if text.startswith("📊 KG:"):
            found["kg_prefix"] = text
        elif text.startswith("📊 Docs:"):
            found["docs_prefix"] = text
        elif text.startswith("📝"):
            # Keyed on the emoji alone, NOT on the wording: a REWORDED
            # marker must fail in the finalize test (with the message that
            # names the consequence), not vanish from this dict and blanket-
            # fail setUp with "no such literal".
            found["finalize_line"] = text
    return found


# ───────────────────────────────────────────────────────────────────────────
# Rust side — the matcher's literals + a verbatim port of its number scan
# ───────────────────────────────────────────────────────────────────────────


def _rust_source() -> str:
    return RUST_PARSER.read_text(encoding="utf-8")


def _rust_fn_body(name: str) -> str:
    src = _rust_source()
    start = src.index(f"fn {name}(")
    return src[start : src.index("\n}", start)]


def _rust_summary_prefixes() -> list[str]:
    """The literals the dispatch loop hands to `parse_summary_line`."""
    return re.findall(r'parse_summary_line\(&line,\s*"([^"]+)"\)', _rust_source())


def _rust_prefix_for(token: str) -> str:
    """The `parse_summary_line` prefix whose literal names `token`.

    A plain `next(...)` raises StopIteration here, which pytest reports as an
    ERROR with no explanation. A drifted prefix is a real finding and must
    read like one.
    """
    matches = [p for p in _rust_summary_prefixes() if token in p]
    assert matches, (
        f"kg_sync.rs no longer calls parse_summary_line with a prefix "
        f"containing {token!r} (found: {_rust_summary_prefixes()}); the "
        f"launcher can no longer recognise the line Python emits for it"
    )
    return matches[0]


def _rust_count_markers() -> list[str]:
    """The words `parse_summary_line` looks an integer up against."""
    return re.findall(
        r'extract_number_before\(trimmed,\s*"([^"]+)"\)',
        _rust_fn_body("parse_summary_line"),
    )


def _rust_finalize_prefix() -> str:
    m = re.search(r'starts_with\("([^"]+)"\)', _rust_fn_body("is_finalize_line"))
    assert m, "is_finalize_line no longer matches on a starts_with literal"
    return m.group(1)


def _rust_extract_number_before(s: str, marker: str) -> int | None:
    """Verbatim port of `kg_sync.rs::extract_number_before`: find the marker,
    walk backwards over whitespace, then take the ASCII digit run."""
    idx = s.find(marker)
    if idx < 0:
        return None
    head = s[:idx]
    rev = []
    it = iter(reversed(head))
    for ch in it:
        if ch.isspace():
            continue
        if ch.isascii() and ch.isdigit():
            rev.append(ch)
            break
        return None
    else:
        return None
    for ch in it:
        if ch.isascii() and ch.isdigit():
            rev.append(ch)
        else:
            break
    try:
        return int("".join(reversed(rev)))
    except ValueError:
        return None


def _rust_parse_summary_line(line: str, prefix: str) -> tuple[int, int, int] | None:
    """Verbatim port of `kg_sync.rs::parse_summary_line`, using the marker
    words read out of the Rust source rather than re-typed here."""
    markers = _rust_count_markers()
    trimmed = line.strip()
    bare = prefix[len("📊 ") :] if prefix.startswith("📊 ") else prefix
    if not trimmed.startswith(prefix) and bare not in trimmed:
        return None
    succeeded = _rust_extract_number_before(trimmed, markers[0])
    if succeeded is None:
        return None
    failed = _rust_extract_number_before(trimmed, markers[1])
    if failed is None:
        return None
    skipped = _rust_extract_number_before(trimmed, markers[2])
    return (succeeded, failed, skipped if skipped is not None else 0)


# ───────────────────────────────────────────────────────────────────────────


def _build_tally(synced: int, failed: int, skipped: int):
    Outcome, Tally, ns = _real_sync_tally_class()
    tally = Tally()
    for _ in range(synced):
        tally.add(Outcome(ns["OUTCOME_SYNCED"], "a.md"))
    for _ in range(failed):
        tally.add(Outcome(ns["OUTCOME_FAILED"], "b.md", "boom"))
    for _ in range(skipped):
        tally.add(Outcome(ns["OUTCOME_EMBED_SKIPPED"], "c.md", "unchanged"))
    return tally


class TestEmitterAndParserAgree(unittest.TestCase):
    """The leg that was missing: one test that sees BOTH literals."""

    def setUp(self):
        self.literals = _emitted_print_literals()
        for key in ("kg_prefix", "docs_prefix", "finalize_line"):
            self.assertIn(
                key,
                self.literals,
                f"the emitter no longer PRINTS a {key} literal — either the "
                f"contract line moved or it is now built somewhere this "
                f"AST walk cannot see",
            )

    def test_the_kg_summary_python_emits_is_what_rust_parses(self):
        tally = _build_tally(synced=113, failed=2, skipped=4)
        line = self.literals["kg_prefix"] + tally.summary_fragment()

        kg_prefix = _rust_prefix_for("KG")
        parsed = _rust_parse_summary_line(line, kg_prefix)

        self.assertIsNotNone(
            parsed,
            f"Rust's parse_summary_line({kg_prefix!r}) rejects the line "
            f"Python emits: {line!r}. The launcher would report this healthy "
            f"run as 0 succeeded / all failed.",
        )
        self.assertEqual(
            parsed,
            (113, 2, 4),
            "Rust parses the emitted line but reads different numbers out of it",
        )

    def test_the_docs_summary_python_emits_is_what_rust_parses(self):
        tally = _build_tally(synced=12, failed=0, skipped=1)
        line = self.literals["docs_prefix"] + tally.summary_fragment()

        docs_prefix = _rust_prefix_for("Docs")
        self.assertEqual(_rust_parse_summary_line(line, docs_prefix), (12, 0, 1))

    def test_the_shared_routing_note_does_not_break_the_parse(self):
        """`--all` appends ` (N → shared)`; Rust promises to ignore it."""
        tally = _build_tally(synced=40, failed=1, skipped=2)
        line = self.literals["kg_prefix"] + tally.summary_fragment() + " (7 → shared)"
        self.assertEqual(_rust_parse_summary_line(line, _rust_prefix_for("KG")), (40, 1, 2))

    def test_the_finalize_marker_python_emits_is_what_rust_recognises(self):
        emitted = self.literals["finalize_line"]
        rust_prefix = _rust_finalize_prefix()
        self.assertTrue(
            emitted.lstrip().startswith(rust_prefix),
            f"is_finalize_line matches on {rust_prefix!r}, which is not a "
            f"prefix of the line Python emits ({emitted!r}); the GUI would "
            f"sit on a stalled-looking 'embedding (N/N)' for the whole "
            f"600 s regen",
        )

    def test_the_finalize_marker_is_not_also_a_summary_line(self):
        """Dispatch order in Rust checks finalize FIRST; if the finalize
        marker also parsed as a summary the two phases would collide."""
        emitted = self.literals["finalize_line"]
        for prefix in _rust_summary_prefixes():
            self.assertIsNone(
                _rust_parse_summary_line(emitted, prefix),
                f"the finalize marker also matches parse_summary_line({prefix!r})",
            )

    def test_a_legacy_two_count_line_still_parses(self):
        """Rust promises both shapes (stale bundle under a new launcher).
        Built from the emitter's own prefix so only the count shape varies."""
        kg_prefix = _rust_prefix_for("KG")
        legacy = self.literals["kg_prefix"] + "50 succeeded, 0 failed"
        self.assertEqual(_rust_parse_summary_line(legacy, kg_prefix), (50, 0, 0))

    def test_the_rust_side_still_reads_three_count_markers(self):
        markers = _rust_count_markers()
        self.assertEqual(
            len(markers),
            3,
            "parse_summary_line no longer extracts exactly three counts; this "
            "parity test's port is out of date with the parser it mirrors",
        )


class TestTheContractFixture(unittest.TestCase):
    """The shared fixture a future lane can point both sides at."""

    def test_fixture_is_regenerated_from_the_two_sources(self):
        _write_fixture()
        data = json.loads(FIXTURE.read_text(encoding="utf-8"))
        self.assertEqual(
            data["python_emits"]["kg_prefix"], _emitted_print_literals()["kg_prefix"]
        )
        self.assertIn(
            data["rust_parses"]["kg_prefix"], data["python_emits"]["kg_prefix"]
        )
        self.assertEqual(data["rust_parses"]["count_markers"], _rust_count_markers())


def _write_fixture() -> None:
    py = _emitted_print_literals()
    payload = {
        "_comment": (
            "Generated by tests/test_v0292_fixround_kg_sync_emit_parse_parity.py. "
            "The KG-sync stdout contract: what sync_knowledge_graph.py PRINTS "
            "and what launcher/src-tauri/src/commands/kg_sync.rs PARSES. "
            "Do not hand-edit; change a source and re-run the test."
        ),
        "python_emits": {
            "kg_prefix": py["kg_prefix"],
            "docs_prefix": py["docs_prefix"],
            "summary_fragment": "{succeeded} succeeded, {failed} failed, {skipped} skipped",
            "finalize_line": py["finalize_line"],
        },
        "rust_parses": {
            "kg_prefix": _rust_prefix_for("KG"),
            "docs_prefix": _rust_prefix_for("Docs"),
            "count_markers": _rust_count_markers(),
            "finalize_prefix": _rust_finalize_prefix(),
        },
    }
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
