# SPDX-License-Identifier: AGPL-3.0-or-later
"""Reproducer for bug 0.6: analyze_code_graph schema-bootstrap retry cap.

Spins up a temp Weaviate class with a lowercase name, then invokes the
analyze script's schema-bootstrap with a same-name-different-case prefix
and asserts:

  1. The script exits non-zero within 5 seconds (was: infinite retry
     wedge — 26 minutes observed on user's machine, ^C-only exit).
  2. The stderr emit contains the actionable case-collision message
     (operator gets told to delete the colliding class via the
     launcher wizard or curl).

Requires a live Weaviate at localhost:8081. CI without Weaviate
auto-skips via the `requires_weaviate` marker — flip it to a real
skip-marker via pytest's `addopts` if the suite is split.

Why direct-invoke `analyze_code_graph.py` rather than a unit-test on
`_create_class_with_retry`? The bug was the END-TO-END wedge — the
helper alone doesn't reproduce the wedge; we need to exercise the
real main() so a future refactor can't accidentally bypass the
fail-fast path (e.g. by catching the case-collision exception too
broadly in a parent try-block).
"""

import os
import subprocess
import sys
import time
import uuid
from pathlib import Path

import pytest


# ─────────────────────────────────────────────────────────────────────
# Test config
# ─────────────────────────────────────────────────────────────────────

WEAVIATE_URL = "http://localhost:8081"

# Where the analyze script lives. We use the templates copy since that's
# the only one in the repo (the project-installed copy at
# .claude/scripts/ is generated by the launcher's bundle install).
ANALYZE_SCRIPT = (
    Path(__file__).parent.parent / "templates" / "scripts" / "analyze_code_graph.py"
)

# Reasonable upper bound for "fast fail". The helper's retry budget
# is 3 attempts × ~0.5-2s backoff plus per-attempt RTT, with a
# documented worst-case of ~3.5s. We allow 5s here to absorb CI jitter
# and Weaviate connect latency. If this test ever flakes by taking
# >5s, the helper has regressed — DO NOT just bump the limit;
# investigate first.
MAX_FAIL_FAST_SECONDS = 5.0


def _weaviate_reachable() -> bool:
    """Cheap probe — used to skip this test on machines without a
    running Weaviate. Doesn't bother distinguishing between "down" and
    "wrong port" — both mean "can't test the wedge, skip"."""
    try:
        import urllib.request
        urllib.request.urlopen(
            f"{WEAVIATE_URL}/v1/.well-known/ready", timeout=2
        )
        return True
    except Exception:
        return False


# Skip this entire file if Weaviate isn't up. The skipif goes at
# module level so collection-time errors don't surface as test
# failures — the file is silently skipped, matching the convention
# used by tests/test_install_*.py.
pytestmark = pytest.mark.skipif(
    not _weaviate_reachable(),
    reason="requires_weaviate: Weaviate not reachable at " + WEAVIATE_URL,
)


# ─────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────


@pytest.fixture
def unique_class_basename() -> str:
    """Per-test unique class basename — avoids cross-test pollution
    when tests run in parallel (-n auto) or when a prior run left
    junk behind."""
    # 8 hex chars of randomness is plenty (collision probability ~1/4B).
    suffix = uuid.uuid4().hex[:8]
    return f"VctReproducer{suffix}"


@pytest.fixture
def temp_repo_with_python_file(tmp_path: Path) -> Path:
    """Create a tiny project folder with one Python file so the
    analyze script has something to analyze (otherwise it short-
    circuits before reaching the schema-bootstrap)."""
    repo = tmp_path / "fake_repo"
    repo.mkdir()
    (repo / "main.py").write_text(
        "def hello(name: str) -> str:\n"
        '    """Greet someone."""\n'
        "    return f'hello {name}'\n"
    )
    # Make it look like a git repo so the analyze script's incremental
    # logic doesn't bail.
    subprocess.run(
        ["git", "init", "-q", str(repo)],
        check=False,
        capture_output=True,
    )
    return repo


def _create_lowercase_class(class_name: str) -> None:
    """Create a Weaviate class via HTTP — bypasses the weaviate-client
    library so the test has no dep on the v4 schema-builder API."""
    import urllib.request, json
    body = json.dumps({
        "class": class_name,
        "vectorizer": "none",
        "properties": [
            {"name": "marker", "dataType": ["text"]}
        ],
    }).encode("utf-8")
    req = urllib.request.Request(
        f"{WEAVIATE_URL}/v1/schema",
        data=body,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    resp = urllib.request.urlopen(req, timeout=5)
    assert resp.status in (200, 201), f"create class HTTP {resp.status}"


def _delete_class_safely(class_name: str) -> None:
    """Best-effort delete — used in fixture teardown. Swallows errors
    because the test may have already deleted it (or never created it
    if an earlier setup step failed)."""
    import urllib.request
    try:
        req = urllib.request.Request(
            f"{WEAVIATE_URL}/v1/schema/{class_name}",
            method="DELETE",
        )
        urllib.request.urlopen(req, timeout=5)
    except Exception:
        pass


# ─────────────────────────────────────────────────────────────────────
# The actual reproducer test
# ─────────────────────────────────────────────────────────────────────


def test_analyze_fails_fast_on_case_insensitive_class_collision(
    unique_class_basename: str,
    temp_repo_with_python_file: Path,
) -> None:
    """End-to-end reproducer for the v0.2.15 codegraph wedge.

    Steps:
      1. Pre-create a lowercase-suffix Weaviate class
         `<basename>_codemodule` (note: lowercase 'codemodule', NOT the
         normal `_CodeModule` PascalCase).
      2. Invoke `analyze_code_graph.py --project <UpperCaseBasename>` —
         which will try to create `<UpperCaseBasename>_CodeModule`.
      3. Weaviate refuses with `"found similar class"` because class
         names are case-insensitively unique.
      4. Pre-fix: analyze retries forever.
         Post-fix: analyze exits non-zero within MAX_FAIL_FAST_SECONDS,
         and stderr contains the actionable error message with delete
         instructions.

    Project-name construction: the analyze script's canonical
    sanitizer maps `<basename>` (already PascalCase ASCII) to itself,
    so the requested class becomes `<basename>_CodeModule`. The
    pre-created collider `<basename>_codemodule` collides with it
    case-insensitively (`CodeModule` ≈ `codemodule`).
    """
    project_name = unique_class_basename
    collider_class = f"{project_name}_codemodule"  # lowercase suffix — the collision trigger

    _create_lowercase_class(collider_class)

    try:
        # Make sure VCT_INSTALL_ROOT points at the worktree root so the
        # script's vco_lib.project_naming import succeeds. (Falls back
        # to inline fallback if missing, but the canonical path is
        # what the launcher uses in practice.)
        env = dict(os.environ)
        env["VCT_INSTALL_ROOT"] = str(Path(__file__).parent.parent.resolve())
        # v0.2.73 (CG-3): Joern CFG/PDG removed — no VCT_JOERN_AVAILABLE / --no-cfg
        # to set; the analyzer no longer probes Joern.

        # Resolve a python that has weaviate-client available. Prefer
        # the local venv if any; otherwise fall back to the running
        # interpreter (which we trust has weaviate-client because the
        # other tests in this dir import it).
        python_exe = sys.executable

        start = time.monotonic()
        proc = subprocess.run(
            [
                python_exe,
                str(ANALYZE_SCRIPT),
                str(temp_repo_with_python_file),
                "--project", project_name,
            ],
            capture_output=True,
            text=True,
            timeout=MAX_FAIL_FAST_SECONDS + 10,  # safety net: a real hang
                                                  # propagates as TimeoutExpired
            env=env,
        )
        elapsed = time.monotonic() - start

        # ─── Assertion 1: non-zero exit (didn't silently continue) ──
        assert proc.returncode != 0, (
            f"Analyze script returned 0 on case-insensitive collision — "
            f"the fail-fast path is broken. stdout={proc.stdout!r} "
            f"stderr={proc.stderr!r}"
        )

        # ─── Assertion 2: actionable error message in stderr ────────
        # The helper prints the EXACT phrase "case-insensitively collides
        # with existing class" — pin that string so a future helper
        # refactor that drops the actionable message fails this test.
        assert "case-insensitively collides with existing class" in proc.stderr, (
            f"Actionable error message missing from stderr. "
            f"stderr={proc.stderr!r}"
        )
        # The colliding class name should appear in the message so the
        # operator can find it in the schema.
        assert collider_class in proc.stderr, (
            f"Colliding class name '{collider_class}' missing from "
            f"actionable stderr message. stderr={proc.stderr!r}"
        )
        # And the curl-delete recipe so the operator has a recovery path
        # even without the launcher running.
        assert "curl -X DELETE" in proc.stderr, (
            f"Recovery instructions (curl delete) missing from stderr. "
            f"stderr={proc.stderr!r}"
        )

        # ─── Assertion 3: fast-fail timing (didn't wedge) ───────────
        assert elapsed < MAX_FAIL_FAST_SECONDS, (
            f"Fail-fast took {elapsed:.1f}s, expected < {MAX_FAIL_FAST_SECONDS}s. "
            f"The retry cap regressed; check `_create_class_with_retry`'s "
            f"backoff schedule."
        )

        # ─── Assertion 4: distinct exit code for schema collision ──
        # main() returns 2 (not generic 1) so callers can special-case.
        # If a future patch reverts to a plain `return 1`, this catches it.
        assert proc.returncode == 2, (
            f"Expected exit code 2 for case-collision (distinct from "
            f"generic-failure 1), got {proc.returncode}. The launcher's "
            f"IPC may rely on the specific code to render a tailored toast."
        )

    finally:
        _delete_class_safely(collider_class)
        # Also try to delete the PascalCase variant in case the analyze
        # script DID create it (would be a sign the fix isn't working).
        _delete_class_safely(f"{project_name}_CodeModule")
