# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 VibeCoded Tools
"""v0.2.100 U16 — VCO no longer asks the user to pick between its OWN two
generated compose override files.

Field shape (genericized): ``infrastructure/docker-compose.override.yml`` and
``compose.override.yaml`` both carry "Auto-generated by VCT (v0.2.96 service
adoption)" and differ only in the newer one adding ``default: {}`` to
code_embed's networks → ``compose_override_filename_conflict`` asked the user.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from vco_lib import project_init as pi  # noqa: E402
from vco_lib.deferral_report import DeferralReport  # noqa: E402

HEADER = "# Auto-generated by VCT (v0.2.96 service adoption).\n# Edits will be overwritten.\n\n"
OLDER = HEADER + ("networks:\n  vibecoded-network:\n    external: true\nservices:\n"
                  "  code_embed:\n    networks:\n      vibecoded-network:\n        aliases:\n"
                  "        - code_embed\nvolumes: {}\n")
NEWER = HEADER + ("networks:\n  vibecoded-network:\n    external: true\nservices:\n"
                  "  code_embed:\n    networks:\n      default: {}\n      vibecoded-network:\n"
                  "        aliases:\n        - code_embed\nvolumes: {}\n")


def _pair(root: Path, legacy: str, canonical: str, *, legacy_newer: bool) -> tuple[Path, Path]:
    infra = root / "infrastructure"
    infra.mkdir(parents=True)
    lp, cp = infra / pi._LEGACY_COMPOSE_OVERRIDE_NAME, infra / pi._CANONICAL_COMPOSE_OVERRIDE_NAME
    lp.write_text(legacy, encoding="utf-8")
    cp.write_text(canonical, encoding="utf-8")
    old, new = (cp, lp) if legacy_newer else (lp, cp)
    os.utime(old, (1_000_000, 1_000_000))
    os.utime(new, (2_000_000, 2_000_000))
    return lp, cp


def _ids(root: Path) -> list[str]:
    return [e.condition_id for e in DeferralReport.read(root).entries]


def test_vco_generated_pair_is_reconciled_backed_up_and_not_deferred(tmp_path):
    """ACT: canonical = the newest generator output, legacy backed up and
    re-mirrored, NO conflict deferral."""
    lp, cp = _pair(tmp_path, NEWER, OLDER, legacy_newer=True)
    res = pi._detect_and_rename_legacy_compose_override(tmp_path)
    assert cp.read_text() == NEWER and lp.read_text() == NEWER
    assert "compose_override_filename_conflict" not in _ids(tmp_path)
    assert res is not None and res["conflicts"] == []
    assert "compose_override_filename_conflict" in res["auto_resolved_condition_ids"]
    backups = list((tmp_path / ".claude" / "backups" / "bundle-adoptions").rglob("*override*"))
    assert [b.read_text() for b in backups] == [OLDER]  # the replaced canonical bytes


def test_user_edited_override_keeps_the_deferral(tmp_path):
    """LEAVE-ALONE: a hand-written half (no VCO header) is a real choice."""
    lp, cp = _pair(tmp_path, NEWER, "services:\n  ollama:\n    ports: ['1:2']\n",
                   legacy_newer=True)
    pi._detect_and_rename_legacy_compose_override(tmp_path)
    assert "compose_override_filename_conflict" in _ids(tmp_path)
    assert cp.read_text().startswith("services:")  # untouched
    assert not (tmp_path / ".claude" / "backups").exists()


def test_two_different_generators_keep_the_deferral(tmp_path):
    """LEAVE-ALONE: volume binds (launcher storage) vs adoption — different
    generators encode different things; VCO does not pick between them."""
    storage = "# Auto-generated by VCT Launcher (Bug 31). Edits will be overwritten\n" + \
        "services: {}\nvolumes:\n  ollama_data:\n    external: true\n    name: legacy_ollama\n"
    _pair(tmp_path, NEWER, storage, legacy_newer=False)
    pi._detect_and_rename_legacy_compose_override(tmp_path)
    assert "compose_override_filename_conflict" in _ids(tmp_path)
