# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 VibeCoded Tools
"""v0.2.89 §8.6 — shipped KG-embedding sidecars: schema, coverage, hash parity.

v0.2.70 shipped the ingest plumbing (a documented NO-OP); v0.2.89 ships the
DATA: ``templates/knowledge/.node_embeddings.qwen3_embed.json`` +
``.node_embeddings.arctic2_embed.json``, generated by
``scripts/build_shipped_kg_embeddings.py``. This module locks the invariants
that make the pre-ship actually fire:

1. SCHEMA VALIDITY — both slot files parse, declare ``schema_version`` 1,
   the slot matching their filename, ``dim`` 1024, and well-formed entries
   (64-hex signature keys, 1-indexed chunk_nums, finite 1024-dim vectors).

2. COVERAGE (the goes-red-on-unregenerated-edit invariant) — EVERY current
   INGESTABLE template node's signature is present in BOTH slot files with
   the chunk count the ingest side would expect, and no stale orphan
   entries linger. "Ingestable" mirrors the consumer: TAG_HIERARCHY /
   VOCABULARY (sync_all_nodes EXCLUDED_FILES) and archived-class nodes
   (``_is_archived_node`` — sync_node never embeds them) ship no vectors.
   Editing a curated node without regenerating turns this red at CI time
   (mirrors ``test_v0270_shipped_kg_summaries``'s reuse invariant).

3. HASH PARITY (the §8.1 trap) — the generator's key function is the SAME
   function the sync ingest looks up by: ``_content_signature_excluding_
   updated`` (FULL 64-hex sha256 of frontmatter-minus-``updated:`` + body),
   NOT the ``.node_formats.json`` summary hash (``sha256(full text)[:16]``).
   A generator keyed per that (previously mis-documented) README convention
   would 100 %-miss silently. Fixtures include an ``updated:``-only pair
   (EQUAL signatures) and a body-differing pair (UNEQUAL).

Pure repo-introspection + unit tests — no network / Ollama / Weaviate.
"""

from __future__ import annotations

import importlib.util
import json
import math
import os
import re
import sys
import unittest
import uuid
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_KNOWLEDGE = REPO_ROOT / "templates" / "knowledge"
GENERATOR_PATH = REPO_ROOT / "scripts" / "build_shipped_kg_embeddings.py"
SYNC_SCRIPT_PATH = REPO_ROOT / "templates" / "scripts" / "sync_knowledge_graph.py"

REGEN_CMD = "python scripts/build_shipped_kg_embeddings.py"

#: The canonical shipped slots and the dim §8.6 pins for both.
EXPECTED_SLOTS = ("qwen3_embed", "arctic2_embed")
EXPECTED_DIM = 1024

_HEX64_RE = re.compile(r"^[0-9a-f]{64}$")

_generator_mod = None
_sync_mod = None


def _generator():
    """Load scripts/build_shipped_kg_embeddings.py by path (cached)."""
    global _generator_mod
    if _generator_mod is None:
        spec = importlib.util.spec_from_file_location(
            f"_gen_shipped_embed_{uuid.uuid4().hex}", GENERATOR_PATH
        )
        mod = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = mod
        spec.loader.exec_module(mod)
        _generator_mod = mod
    return _generator_mod


def _sync():
    """Load the sync script INDEPENDENTLY of the generator's own import.

    The parity tests compare the generator's key function against a
    separately-loaded copy of the sync module, so they stay meaningful even
    if the generator's import strategy is ever changed (e.g. someone
    replaces the delegation with a local copy — the parity test catches the
    drift the moment the copy diverges).
    """
    global _sync_mod
    if _sync_mod is None:
        os.environ.setdefault("VCT_DISABLE_HUB_RESOLVER", "1")
        spec = importlib.util.spec_from_file_location(
            f"_sync_kg_parity_{uuid.uuid4().hex}", SYNC_SCRIPT_PATH
        )
        mod = importlib.util.module_from_spec(spec)
        sys.modules[spec.name] = mod
        try:
            spec.loader.exec_module(mod)
        except ModuleNotFoundError as exc:
            raise unittest.SkipTest(
                f"sync_knowledge_graph.py has runtime deps not installed ({exc})"
            )
        _sync_mod = mod
    return _sync_mod


def _load_sidecar(slot: str) -> dict:
    path = TEMPLATES_KNOWLEDGE / f".node_embeddings.{slot}.json"
    if not path.is_file():
        raise AssertionError(
            f"{path.name} is MISSING — v0.2.89 ships the embedding data; "
            f"regenerate with `{REGEN_CMD}`"
        )
    return json.loads(path.read_text(encoding="utf-8"))


class ShippedSidecarSchemaTest(unittest.TestCase):
    """§8.6: both slot files parse with the exact v0.2.70 schema shape."""

    def test_schema_header_fields(self):
        for slot in EXPECTED_SLOTS:
            with self.subTest(slot=slot):
                data = _load_sidecar(slot)
                self.assertEqual(data.get("schema_version"), 1)
                self.assertEqual(
                    data.get("slot"), slot,
                    "slot field must match the filename slot — the ingest "
                    "file-level slot guard rejects mismatches as absent",
                )
                self.assertEqual(
                    data.get("dim"), EXPECTED_DIM,
                    f"both canonical slots are {EXPECTED_DIM}-dim models",
                )
                self.assertTrue(
                    isinstance(data.get("model_id"), str) and data["model_id"],
                    "model_id provenance field must be a non-empty string",
                )
                self.assertIsInstance(data.get("nodes"), dict)
                self.assertGreater(len(data["nodes"]), 0)

    def test_model_id_maps_to_slot(self):
        """A cross-model file (e.g. arctic sidecar built with qwen3) must
        never ship — the model→slot map is the arbiter."""
        try:
            if str(REPO_ROOT) not in sys.path:
                sys.path.insert(0, str(REPO_ROOT))
            from vco_lib.embedding_service import _resolve_text_slot
        except Exception as exc:  # pragma: no cover — healthy installs have vco_lib
            raise unittest.SkipTest(f"vco_lib not importable ({exc})")
        for slot in EXPECTED_SLOTS:
            with self.subTest(slot=slot):
                data = _load_sidecar(slot)
                map_slot, map_dim = _resolve_text_slot(data["model_id"])
                self.assertEqual(map_slot, slot)
                self.assertEqual(map_dim, data["dim"])

    def test_entries_are_well_formed(self):
        for slot in EXPECTED_SLOTS:
            with self.subTest(slot=slot):
                data = _load_sidecar(slot)
                for sig, entry in data["nodes"].items():
                    self.assertRegex(
                        sig, _HEX64_RE,
                        "sidecar keys must be the FULL 64-hex content "
                        "signature (NOT the 16-hex .node_formats.json hash — "
                        "the §8.1 hash-scheme trap)",
                    )
                    chunks = entry.get("chunks")
                    self.assertIsInstance(chunks, list)
                    self.assertGreater(len(chunks), 0)
                    self.assertEqual(
                        entry.get("total_chunks"), len(chunks),
                        f"{slot}:{sig[:12]}… total_chunks != len(chunks)",
                    )
                    nums = sorted(c.get("chunk_num") for c in chunks)
                    self.assertEqual(
                        nums, list(range(1, len(chunks) + 1)),
                        f"{slot}:{sig[:12]}… chunk_nums must be exactly 1..N",
                    )
                    for c in chunks:
                        vec = c.get("vector")
                        self.assertIsInstance(vec, list)
                        self.assertEqual(
                            len(vec), EXPECTED_DIM,
                            f"{slot}:{sig[:12]}… chunk {c.get('chunk_num')} "
                            f"vector dim != {EXPECTED_DIM}",
                        )
                        self.assertTrue(
                            all(
                                isinstance(x, (int, float)) and math.isfinite(x)
                                for x in vec
                            ),
                            f"{slot}:{sig[:12]}… non-finite vector component",
                        )


class ShippedCoverageInvariantTest(unittest.TestCase):
    """§8.6: EVERY current template node covered in BOTH slot files with the
    chunk count ingest expects — red the moment a node is edited without
    regenerating (the invariant that makes the pre-ship trustworthy)."""

    def test_every_node_covered_with_matching_chunk_counts(self):
        gen = _generator()
        problems: list[str] = []
        for slot in EXPECTED_SLOTS:
            data = _load_sidecar(slot)
            nodes = data["nodes"]
            model_id = data["model_id"]
            current_sigs: set[str] = set()
            for node in gen.iter_shipped_nodes():
                rel = node.relative_to(TEMPLATES_KNOWLEDGE).as_posix()
                text = node.read_text(encoding="utf-8")
                sig = gen.content_signature(text)
                current_sigs.add(sig)
                entry = nodes.get(sig)
                if not isinstance(entry, dict):
                    problems.append(f"{slot}: no entry for {rel}")
                    continue
                expected_chunks = len(gen.chunk_plan(text, model_id))
                got = len(entry.get("chunks") or [])
                if got != expected_chunks:
                    problems.append(
                        f"{slot}: {rel} ships {got} chunk(s), ingest "
                        f"expects {expected_chunks}"
                    )
            orphans = set(nodes) - current_sigs
            if orphans:
                problems.append(
                    f"{slot}: {len(orphans)} stale orphan entries (match no "
                    f"current node)"
                )
        self.assertEqual(
            problems, [],
            "shipped embeddings are STALE vs the current curated nodes — the "
            f"zero-embed seed will silently fall back to compute. Regenerate "
            f"with `{REGEN_CMD}`. Problems:\n  " + "\n  ".join(problems),
        )

    def test_verify_gate_is_green(self):
        """The pre-tag gate leg (`--verify`) agrees: zero problems.

        Runs the generator's own verifier so CI exercises the exact code
        the pre-tag battery invokes."""
        gen = _generator()
        self.assertEqual(
            gen.verify_slots(), [],
            f"`{REGEN_CMD} --verify` would fail — regenerate the sidecars",
        )


class HashParityTest(unittest.TestCase):
    """§8.1/§8.6: generator key == sync lookup key, on discriminating fixtures.

    The README used to document ``sha256(full text)[:16]`` as the sidecar
    key; the REAL key is the full 64-hex ``_content_signature_excluding_
    updated``. These fixtures pin both the delegation (generator == sync on
    every input) and the signature's semantics (``updated:``-only edits keep
    the key; body edits change it).
    """

    BASE = (
        "---\n"
        "title: Parity Fixture\n"
        "type: concept\n"
        "created: 2026-01-01T00:00:00Z\n"
        "updated: 2026-01-01T00:00:00Z\n"
        "status: active\n"
        "---\n"
        "The fixture body.\n"
    )
    UPDATED_ONLY = BASE.replace(
        "updated: 2026-01-01T00:00:00Z", "updated: 2026-07-30T12:34:56Z"
    )
    BODY_DIFF = BASE.replace("The fixture body.", "A DIFFERENT fixture body.")
    NO_FRONTMATTER = "plain text, no frontmatter at all\n"

    def test_generator_key_equals_sync_lookup_key(self):
        gen = _generator()
        sync = _sync()
        for name, text in (
            ("base", self.BASE),
            ("updated_only", self.UPDATED_ONLY),
            ("body_diff", self.BODY_DIFF),
            ("no_frontmatter", self.NO_FRONTMATTER),
        ):
            with self.subTest(fixture=name):
                self.assertEqual(
                    gen.content_signature(text),
                    sync._content_signature_excluding_updated(text),
                    "generator key function drifted from the sync ingest's "
                    "lookup key — shipped vectors would 100%-miss silently",
                )

    def test_updated_only_pair_hashes_equal(self):
        gen = _generator()
        self.assertNotEqual(self.BASE, self.UPDATED_ONLY)  # fixture sanity
        self.assertEqual(
            gen.content_signature(self.BASE),
            gen.content_signature(self.UPDATED_ONLY),
            "an `updated:`-line-only edit must keep the signature stable "
            "(machine-written timestamp bumps must not invalidate shipped "
            "vectors)",
        )

    def test_body_differing_pair_hashes_unequal(self):
        gen = _generator()
        self.assertNotEqual(
            gen.content_signature(self.BASE),
            gen.content_signature(self.BODY_DIFF),
            "a body edit MUST change the signature (staleness guard depends "
            "on it)",
        )

    def test_key_is_full_64_hex_not_the_summary_hash(self):
        """The §8.1 trap, pinned directly: the key is the FULL sha256
        hexdigest — 64 hex chars — not the summary sidecar's 16-hex form."""
        gen = _generator()
        sig = gen.content_signature(self.BASE)
        self.assertRegex(sig, _HEX64_RE)
        import hashlib

        summary_hash = hashlib.sha256(self.BASE.encode("utf-8")).hexdigest()[:16]
        self.assertNotEqual(
            sig[:16], summary_hash,
            "signature (excludes `updated:`) must differ from the "
            ".node_formats.json full-text hash prefix on an updated:-bearing "
            "fixture — if these ever collide the fixture no longer "
            "discriminates the two schemes",
        )


if __name__ == "__main__":
    unittest.main()
