#!/usr/bin/env bash
# compact-context-reinject.sh
# Fires on SessionStart with matcher "compact"
# Re-injects critical session context that compaction may have dropped.
# Stdout is added to Claude's context automatically by the CLI.
#
# LITM ordering (Lost-In-The-Middle): Claude weights start and end of context
# most heavily. Place most critical info at start AND end.
#
# Total budget: ~250 lines max. CONTEXT_STATE gets full allocation, others capped.
# Track C (v0.2.65) line-budget split: the shared CONTEXT_STATE.md rollup stays
# uncapped at the START (most critical). The per-session file (if present) is
# injected right after it with a 120-line sub-cap, so the two together plus the
# downstream caps (plan 30 + commits 8 + snapshot 50 + pruned 30 = ~118) stay
# within the ~250-line budget.

# Scrub sensitive env vars (this hook doesn't need credentials)
unset SUPABASE_KEY SUPABASE_URL GITHUB_TOKEN GH_TOKEN OPENAI_API_KEY ANTHROPIC_API_KEY AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID TELEGRAM_BOT_TOKEN POSTGRES_PASSWORD VERCEL_TOKEN CLAUDE_API_KEY 2>/dev/null
[ -n "${VCT_DISABLE_HOOKS:-}" ] && exit 0

. "$(dirname "${BASH_SOURCE[0]}")/_lib/stderr-cap.sh"
# Resolve Python portably for the session_id stdin parse below (python3 →
# python → py). Same fallback chain as diff-context-inject.sh.
# shellcheck source=_lib/find-python.sh disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/_lib/find-python.sh"
# Shared session_id parse + path-safety sanitise (vco_hook_session_id). One
# implementation for all four context hooks; see _lib/session-id.sh.
# shellcheck source=_lib/session-id.sh disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/_lib/session-id.sh"

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$PWD}"

# Track C (v0.2.65): SessionStart payload carries session_id on stdin. The
# shared vco_hook_session_id parses it (json.loads → 'session_id') so we can
# locate this session's own CONTEXT_STATE file. Empty when the payload is
# absent/malformed → the per-session block below is skipped (gated on
# `[ -n "$SESSION_ID" ]`). Defense-in-depth (review C-1): the helper also
# sanitises the id to [A-Za-z0-9_-] before it reaches the file path below — a
# hostile `/` or `..` collapses to the safe sentinel "default". Must match the
# .ps1 sibling's Get-VcoHookSessionId.
HOOK_STDIN=$(cat 2>/dev/null || echo "")
SESSION_ID=$(vco_hook_session_id "$HOOK_STDIN")

# 1. Current task state -- START position (most critical, uncapped)
if [ -f "$PROJECT_DIR/.claude/CONTEXT_STATE.md" ]; then
    echo "## Current Task State (re-injected after compaction)"
    cat "$PROJECT_DIR/.claude/CONTEXT_STATE.md"
    echo ""
fi

# 1b. Per-session task state -- START position (Track C). IF this session has
# written its own .claude/context/CONTEXT_STATE_<session_id>.md, reinject it
# right after the shared rollup — it's the most task-relevant state for THIS
# chat. Capped at 120 lines to respect the ~250-line total budget. Gated on
# both a resolved session_id AND file existence, so single-session projects
# (no per-session file) pay nothing.
if [ -n "$SESSION_ID" ]; then
    SESSION_CONTEXT_FILE="$PROJECT_DIR/.claude/context/CONTEXT_STATE_${SESSION_ID}.md"
    if [ -f "$SESSION_CONTEXT_FILE" ]; then
        echo "## This Session's Task State (re-injected after compaction)"
        head -120 "$SESSION_CONTEXT_FILE"
        echo ""
    fi
fi

# 2. Active plan summary -- MIDDLE position (cap: 30 lines)
LATEST_PLAN=$(ls -t "$PROJECT_DIR/.claude/context/plans/"*.md 2>/dev/null | grep -v archive | head -1)
if [ -n "$LATEST_PLAN" ]; then
    echo "## Active Plan: $(basename "$LATEST_PLAN")"
    head -30 "$LATEST_PLAN"
    echo ""
fi

# 3. Recent git activity -- MIDDLE position (cap: 8 commits)
echo "## Recent Commits"
git -C "$PROJECT_DIR" log --oneline -8 2>/dev/null || true
echo ""

# 4. Pre-compaction snapshot -- END position (cap: 50 lines)
#    Contains git status + recently changed files, saved by pre-compact-save.sh
SNAPSHOT="$PROJECT_DIR/.claude/context/pre-compact-snapshot.md"
if [ -f "$SNAPSHOT" ]; then
    echo "## Pre-Compaction Snapshot"
    head -50 "$SNAPSHOT"
    echo ""
fi

# 5. Pruned activity summary -- END position (cap: 30 lines)
#    Frequently-edited paths + bash commands run repeatedly. Generated by
#    .claude/scripts/precompact_prune.py via pre-compact-save.sh.
#    Truncated AFTER re-injection so a non-compact SessionStart doesn't
#    re-show last compact's summary as stale state.
PRUNED="$PROJECT_DIR/.claude/context/pruned-context-summary.md"
if [ -s "$PRUNED" ]; then
    head -30 "$PRUNED"
    echo ""
    : > "$PRUNED"
fi
