# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 VibeCoded Tools
"""The orchestrator root's ``.env``, as ``install.py`` writes it (v0.2.97).

One writer per concern:

  * the canonical keys (service URLs, embedding profile, KG collections,
    shared-KG flags) live in the VCO-managed block, written by
    :func:`vco_lib.env_template.apply_env_template` — the one ``.env``
    writer, the same one the launcher uses for every project;
  * the install-time-only keys (``WEAVIATE_GRPC_PORT``, the embedding
    model / dims / backend, ``CODE_EMBED_*`` service settings,
    ``EMBEDDING_PROVIDER``, ``VCT_TELEMETRY``) are rendered HERE, by
    :func:`render_install_env_tail`, as the text a NEW file starts with.
    They are user-owned lines from then on: nothing rewrites them.

Before v0.2.97 ``install.py`` wrote the whole file itself on a fresh
install, appended a managed block with placeholder values
(``PROJECT_NAME=<project>``, ``KG_COLLECTION=Project_KnowledgeGraph``) on a
re-install, and appended annotated lines on ``--update`` — three writers,
one file. All three now go through :func:`write_orchestrator_env`.

No third-party imports: ``install.py`` reaches this before its venv is
guaranteed complete.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Optional, Sequence

_SHARED_KG_DEFAULT = "VibeCodedOrchestrator_KnowledgeGraph"


def orchestrator_env_template_keys(
    environ: Mapping[str, str],
    *,
    default_weaviate_port: int,
    default_ollama_port: int,
    default_code_embed_port: int,
    active_embedding: Optional[str] = None,
) -> dict[str, str]:
    """The managed-block keys for the orchestrator root, from install.py's
    resolved state (``environ`` — ``_ensure_collections`` and the embedding
    reconcile publish their results there).

    ``PROJECT_NAME`` / ``CODE_GRAPH_PROJECT`` are rendered only when known:
    a made-up name (the old ``<project>`` / ``Project`` placeholders) is
    worse than none — every shell that sources the file would carry it.
    """
    weaviate_port = environ.get("WEAVIATE_PORT", str(default_weaviate_port))
    ollama_port = environ.get("OLLAMA_PORT", str(default_ollama_port))
    code_embed_port = environ.get("CODE_EMBED_PORT", str(default_code_embed_port))
    keys: dict[str, str] = {}
    project_name = environ.get("PROJECT_NAME", "").strip()
    if project_name:
        keys["PROJECT_NAME"] = project_name
    code_graph_project = environ.get("CODE_GRAPH_PROJECT", "").strip() or project_name
    if code_graph_project:
        keys["CODE_GRAPH_PROJECT"] = code_graph_project
    keys.update({
        "KG_COLLECTION": environ.get("KG_COLLECTION", "KnowledgeGraph"),
        "DEVELOPMENT_COLLECTION": environ.get("DEVELOPMENT_COLLECTION", "Development"),
        "SHARED_KG_COLLECTION": environ.get("SHARED_KG_COLLECTION", _SHARED_KG_DEFAULT),
        "SHARED_KG_WRITE_DISABLED": "false",
        "SHARED_KG_OPT_OUT": "false",
        "SHARED_KG_READ_DISABLED": "false",
        "ACTIVE_EMBEDDING": active_embedding or environ.get("ACTIVE_EMBEDDING", "qwen3"),
        "WEAVIATE_URL": f"http://localhost:{weaviate_port}",
        "WEAVIATE_PORT": weaviate_port,
        "OLLAMA_URL": f"http://localhost:{ollama_port}",
        "OLLAMA_PORT": ollama_port,
        "CODE_EMBED_URL": f"http://localhost:{code_embed_port}",
        "CODE_EMBED_PORT": code_embed_port,
    })
    return keys


def render_install_env_tail(
    embed_config: Mapping[str, Any],
    *,
    weaviate_grpc_port: str,
    code_embed_port: str,
    telemetry_enabled: bool,
    concurrency_lines: Sequence[str] = (),
) -> str:
    """The install-time-only part of a fresh orchestrator ``.env``: the
    same lines ``install.py`` wrote before v0.2.97, minus the canonical
    keys (those are the managed block's now). Ends with a blank line; the
    managed block follows it."""
    lines = [
        "# VibeCoded Tools — Orchestrator Configuration",
        "# Generated by install.py — edit as needed",
        "# Service URLs, the embedding profile and the KG collections live in",
        "# the VCO-MANAGED block at the end. To override one, set it anywhere",
        "# OUTSIDE that block — VCO then stops writing it.",
        "",
        "# Weaviate",
        f"WEAVIATE_GRPC_PORT={weaviate_grpc_port}",
        "",
        "# Embedding models",
        f"EMBEDDING_MODEL={embed_config['text_model']}",
        f"EMBEDDING_DIMS={embed_config['text_dims']}",
        f"CODE_EMBED_BACKEND={embed_config['code_backend']}",
        f"CODE_EMBED_MODEL={embed_config['code_model']}",
        f"CODE_EMBED_DIMS={embed_config['code_dims']}",
        f"CODE_EMBED_SERVICE_URL=http://localhost:{code_embed_port}",
        # v0.2.77 5c task 2: hardware-derived in-flight cap (honour-explicit).
        *concurrency_lines,
        # v0.2.50 audit F1: NVIDIA hosts opt into the CUDA code-embed image;
        # the compose file reads ${CODE_EMBED_DOCKERFILE:-Dockerfile}.
        *(["CODE_EMBED_DOCKERFILE=Dockerfile.cuda"]
          if embed_config.get("gpu_vendor") == "nvidia" else []),
        "",
        "# Cross-project shared KG (all vco installs on this machine read",
        "# from it alongside their own KG by default — v0.2.46 added a",
        "# symmetric per-project READ opt-out gate, asymmetric-by-default).",
        "# Seeded at install time from vibecoded-orchestrator/knowledge/.",
        "# Set SHARED_KG_WRITE_DISABLED=true to gate WRITES from this project,",
        "# SHARED_KG_READ_DISABLED=true to gate READS. SHARED_KG_OPT_OUT is",
        "# the legacy write alias kept for ~3 releases (target removal:",
        "# 2026-08); no read alias because the read path was unconditional",
        "# pre-v0.2.46.",
        "",
    ]
    if embed_config.get("openai_key"):
        # v0.2.97: the KEY itself is never written here — install.py stores
        # it (vco_lib.openai_key) in the launcher keychain or the file store,
        # where every reader resolves it.
        lines += [
            "# OpenAI embeddings — the API key is in the launcher keychain /",
            "# ~/.vct-secrets (slot `openai_api_key`), never in this file.",
            "EMBEDDING_PROVIDER=openai",
            "",
        ]
    else:
        lines += ["# Embedding provider", "EMBEDDING_PROVIDER=ollama", ""]
    lines += [
        "# Anonymous telemetry (default: off — README promise)",
        "# Set to 'true' to enable; collector + uploader both honour this.",
        # B7: canonical key is VCT_TELEMETRY; VIBECODED_TELEMETRY is a
        # read-time alias in the telemetry module only.
        f"VCT_TELEMETRY={'true' if telemetry_enabled else 'false'}",
        "",
    ]
    return "\n".join(lines) + "\n"


def write_orchestrator_env(
    root: Path,
    keys: Mapping[str, str],
    *,
    tail: Optional[str] = None,
) -> dict[str, list[str]]:
    """Write ``<root>/.env`` through the one ``.env`` writer.

    A missing file is created as ``tail`` + the managed block. An existing
    file is refreshed FILL-ONLY (``keep_existing_values``): install.py's
    resolution on a re-install or ``--update`` is not authoritative over a
    file the user (or an earlier install) settled, so keys are added,
    never changed or dropped; a key the user sets outside the block is
    never rendered at all. Returns :func:`apply_env_template`'s report.
    """
    from vco_lib.env_template import apply_env_template

    return apply_env_template(
        keys, project_folder=root, scaffold=tail, keep_existing_values=True
    )


__all__ = [
    "orchestrator_env_template_keys",
    "render_install_env_tail",
    "write_orchestrator_env",
]
