#!/usr/bin/env bash
# bump-version.sh — single-command release version bump.
#
# v0.2.57: the orchestrator's version lives in MANY files (a Cargo
# workspace + npm + Tauri + the module manifest + the Python package).
# Hand-editing each one per release is how the hub drifted to 0.2.54
# while the launcher shipped 0.2.56. This script bumps ALL of them from
# ONE argument so a release is `scripts/bump-version.sh 0.2.57`, not a
# nine-file scavenger hunt.
#
# What it touches:
#   * launcher/src-tauri/Cargo.toml      [workspace.package] version  (the
#     SINGLE Cargo source — vct-hub / vct-updater / vct-launcher-core /
#     the launcher binary all inherit it via `version.workspace = true`,
#     so this one line covers all 4 crates).
#   * launcher/src-tauri/Cargo.lock      regenerated by `cargo build`
#     (or, if cargo is unavailable, the 4 workspace-crate entries are
#     rewritten in place as a fallback).
#   * pyproject.toml                     [project] version (pre-ship-check's
#     EXPECTED_VERSION source of truth).
#   * launcher/package.json              top-level "version".
#   * launcher/package-lock.json         top-level + packages[""] "version".
#   * launcher/src-tauri/tauri.conf.json "version".
#   * vct-module.json                    "version".
#
# It does NOT touch CHANGELOG.md (that needs a human-written entry) and it
# does NOT commit/tag (the release flow owns that). After running, verify
# with `scripts/pre-ship-check.sh` — it asserts every pin agrees.
#
# Usage:
#   scripts/bump-version.sh 0.2.57
#   scripts/bump-version.sh --check        # print current pins, change nothing
#
# Idempotent: re-running with the same version is a no-op per file.

set -euo pipefail

# Resolve repo root from this script's location (scripts/ is at repo root).
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$ROOT"

WS_CARGO="launcher/src-tauri/Cargo.toml"
CARGO_LOCK="launcher/src-tauri/Cargo.lock"
PYPROJECT="pyproject.toml"
PKG_JSON="launcher/package.json"
PKG_LOCK="launcher/package-lock.json"
TAURI_CONF="launcher/src-tauri/tauri.conf.json"
MODULE_JSON="vct-module.json"

# The 4 workspace crates that inherit the [workspace.package] version.
WS_CRATES=(vct-launcher-temp vct-hub vct-updater vct-launcher-core)

usage() {
    grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//' | head -40
    exit "${1:-0}"
}

# --- read the current workspace version (the canonical source) -----------
current_ws_version() {
    # The first `version = "X.Y.Z"` UNDER [workspace.package]. We read the
    # line immediately following the [workspace.package] header.
    awk '
        /^\[workspace\.package\]/ { in_wp = 1; next }
        in_wp && /^version *= *"/ {
            match($0, /"[0-9]+\.[0-9]+\.[0-9]+[^"]*"/)
            print substr($0, RSTART+1, RLENGTH-2)
            exit
        }
        /^\[/ && in_wp { in_wp = 0 }
    ' "$WS_CARGO"
}

print_pins() {
    echo "Current version pins:"
    printf "  %-44s %s\n" "$WS_CARGO [workspace.package]" "$(current_ws_version)"
    printf "  %-44s %s\n" "$PYPROJECT" "$(grep -m1 -E '^version *= *"' "$PYPROJECT" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo '?')"
    printf "  %-44s %s\n" "$PKG_JSON" "$(grep -m1 '"version"' "$PKG_JSON" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo '?')"
    printf "  %-44s %s\n" "$PKG_LOCK (root)" "$(grep -m1 '"version"' "$PKG_LOCK" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo '?')"
    printf "  %-44s %s\n" "$TAURI_CONF" "$(grep -m1 '"version"' "$TAURI_CONF" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo '?')"
    printf "  %-44s %s\n" "$MODULE_JSON" "$(grep -m1 '"version"' "$MODULE_JSON" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' || echo '?')"
}

if [ $# -eq 0 ]; then usage 1; fi
if [ "$1" = "--check" ]; then print_pins; exit 0; fi
if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then usage 0; fi

NEW="$1"
if ! printf '%s' "$NEW" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
    echo "ERROR: '$NEW' is not a valid X.Y.Z version" >&2
    exit 2
fi

OLD="$(current_ws_version)"
echo "Bumping version: ${OLD:-<unknown>} -> $NEW"

# Portable in-place sed (GNU vs BSD). We always pass a single explicit
# expression scoped enough that it can't hit unrelated lines.
sed_i() {
    local expr="$1" file="$2"
    if sed --version >/dev/null 2>&1; then
        sed -i -e "$expr" "$file"          # GNU
    else
        sed -i '' -e "$expr" "$file"        # BSD/macOS
    fi
}

# 1) Cargo [workspace.package] — the ONLY Cargo edit (4 crates inherit it).
#    Match the `version = "..."` line that sits directly under the
#    [workspace.package] header, using an address range so we never touch
#    the [package] line above or any dependency `version =`.
sed_i "/^\[workspace\.package\]/,/^\[/ s/^version *= *\"[0-9][^\"]*\"/version = \"$NEW\"/" "$WS_CARGO"

# 2) pyproject.toml [project] version (first top-level `version = "..."`).
sed_i "0,/^version *= *\"[0-9][^\"]*\"/ s//version = \"$NEW\"/" "$PYPROJECT"

# 3+4) package.json + package-lock.json — JSON-aware edit (NOT sed).
#    package-lock.json carries the root version in TWO places: the
#    top-level "version" AND packages[""]["version"]; npm keeps them in
#    sync. A naive "first match" sed leaves the second stale (exactly the
#    drift this script exists to prevent), and a "2nd occurrence" sed is
#    fragile across GNU/BSD. Python sets precisely the right keys and
#    nothing else (dependency versions in the nested tree are untouched).
#    We write with indent=2 + trailing newline to match npm's format so
#    the diff stays minimal.
python3 - "$NEW" "$PKG_JSON" "$PKG_LOCK" <<'PY'
import json, sys
new, pkg_json, pkg_lock = sys.argv[1], sys.argv[2], sys.argv[3]

def load(p):
    with open(p) as f:
        return json.load(f)

def dump(p, d):
    with open(p, "w") as f:
        json.dump(d, f, indent=2)
        f.write("\n")

# package.json: top-level version only.
pj = load(pkg_json)
pj["version"] = new
dump(pkg_json, pj)

# package-lock.json: top-level version + the root package entry "".
pl = load(pkg_lock)
pl["version"] = new
if "packages" in pl and "" in pl["packages"]:
    pl["packages"][""]["version"] = new
dump(pkg_lock, pl)
print(f"  package.json + package-lock.json (root x2) -> {new}")
PY

# 5) tauri.conf.json — "version".
sed_i "0,/\"version\": *\"[0-9][^\"]*\"/ s//\"version\": \"$NEW\"/" "$TAURI_CONF"

# 6) vct-module.json — "version".
sed_i "0,/\"version\": *\"[0-9][^\"]*\"/ s//\"version\": \"$NEW\"/" "$MODULE_JSON"

# 7) Cargo.lock — regenerate via cargo so the 4 workspace crate entries
#    pick up the new version. Fallback: rewrite the 4 entries by name if
#    cargo isn't available (CI image without the toolchain).
if command -v cargo >/dev/null 2>&1; then
    echo "Refreshing Cargo.lock via cargo (offline metadata)..."
    ( cd launcher/src-tauri && cargo update --workspace --offline >/dev/null 2>&1 || cargo build --offline >/dev/null 2>&1 || true )
fi
# Safety-net rewrite (cheap, idempotent): for each workspace crate, set its
# version line in Cargo.lock. Only matches the `version = "..."` line that
# immediately follows `name = "<crate>"`.
for crate in "${WS_CRATES[@]}"; do
    sed_i "/^name = \"$crate\"$/{n;s/^version = \"[0-9][^\"]*\"/version = \"$NEW\"/;}" "$CARGO_LOCK"
done

echo
print_pins
echo
echo "Done. Next:"
echo "  1. Add a CHANGELOG.md [$NEW] entry (human-written)."
echo "  2. Run: scripts/pre-ship-check.sh   (verifies every pin agrees)."
